name: GitHub-Profile-Automations

on:
  schedule:
    # Execute ambos diariamente às 18:00 UTC (03:00 JST)
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  generate-github-profile-3d:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile 3D
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push

  generate-github-profile-summary-cards:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile Summary Cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated card"
          git push

